name: Trigger save-hot-post every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call save-hot-post API
        run: |
          curl -X GET https://cron-api-server.vercel.app/api/save-hot-post
