# .github/workflows/save-hot-post-reborn.yml
name: Save hot post every 7 minutes (reborn)

on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API
        run: curl -v https://cron-api-server.vercel.app/api/save-hot-post
